<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <Resource Include="Assets\icon.png" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Fulltxt.Core\Fulltxt.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.12" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>Assets/app.ico</ApplicationIcon>
  </PropertyGroup>

</Project>
